INSERT INTO tb_worker (NAME, DAILY_INCOME) VALUES ('Bob', 200.0);
INSERT INTO tb_worker (NAME, DAILY_INCOME) VALUES ('Maria', 300.0);
INSERT INTO tb_worker (NAME, DAILY_INCOME) VALUES ('Alex', 250.0);